name: scheduled test

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "1 minute every hour!"
