name: scheduled test

on:
  schedule:
    - cron: '1 * * * *'
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    setps:
      - name: Check out repository
        uses: actions/checkout@v2
       
      - name: Run a script
        run: echo "1 mintes every!"
